/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DAOInterfaces.DAOException;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Acer
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    boolean usuario=false;
    
    Login l;
    AgregarColor aco;
    AgregarSuela as;
    AgregarCliente ac;
    AgregarZapato az;
    BuscarZapato bz;
    BuscarCliente bc;
    Buscarfactura bv;
    Venta v;
    
    public Inicio(Login l) throws SQLException, DAOException {
        
        initComponents();
        aco=new AgregarColor(this);
        as=new AgregarSuela(this);
        ac = new AgregarCliente(this);
        az=new AgregarZapato(this);
        bz = new BuscarZapato(this);
        this.setResizable(false);
        bc = new BuscarCliente(this);
        bv = new Buscarfactura(this);
        v=new Venta(this);
        this.l=l;
        this.getContentPane().setBackground(Color.decode("#FFFFCC"));
        validar();
        
        
        
    }
    
    public void validar(){
        if(this.usuario==false){
           adm.setEnabled(usuario);
        }
        if(this.usuario=true){
           adm.setVisible(usuario);
        }
    }

    //public void setUsuario(boolean usuario) {
    //    this.usuario = usuario;
    //}

    
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agzapato = new javax.swing.JButton();
        agcliente = new javax.swing.JButton();
        bzapato = new javax.swing.JButton();
        bcliente = new javax.swing.JButton();
        gventa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        adm = new javax.swing.JButton();
        resetclave = new javax.swing.JButton();
        agcolor = new javax.swing.JButton();
        agsuela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calzado Semillas de Fe");

        agzapato.setBackground(new java.awt.Color(204, 153, 255));
        agzapato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        agzapato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/zapato.jpg"))); // NOI18N
        agzapato.setAlignmentX(5.0F);
        agzapato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agzapatoActionPerformed(evt);
            }
        });

        agcliente.setBackground(new java.awt.Color(204, 153, 255));
        agcliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        agcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recorte4.jpg"))); // NOI18N
        agcliente.setAlignmentX(5.0F);
        agcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agclienteActionPerformed(evt);
            }
        });

        bzapato.setBackground(new java.awt.Color(204, 153, 255));
        bzapato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bzapato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/zap1.jpg"))); // NOI18N
        bzapato.setAlignmentX(5.0F);
        bzapato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bzapatoActionPerformed(evt);
            }
        });

        bcliente.setBackground(new java.awt.Color(204, 153, 255));
        bcliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recorte8.jpg"))); // NOI18N
        bcliente.setAlignmentX(5.0F);
        bcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclienteActionPerformed(evt);
            }
        });

        gventa.setBackground(new java.awt.Color(204, 153, 255));
        gventa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.jpg"))); // NOI18N
        gventa.setAlignmentX(5.0F);
        gventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gventaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Elaborado Por Sinsy");

        adm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/us.jpg"))); // NOI18N
        adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admActionPerformed(evt);
            }
        });

        resetclave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clave.jpg"))); // NOI18N
        resetclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetclaveActionPerformed(evt);
            }
        });

        agcolor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cl.jpg"))); // NOI18N
        agcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agcolorActionPerformed(evt);
            }
        });

        agsuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/zd1.jpg"))); // NOI18N
        agsuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agsuelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agzapato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetclave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bzapato, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(gventa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(adm, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(agsuela, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bcliente)
                                .addGap(18, 18, 18)
                                .addComponent(bzapato, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agcliente)
                                    .addComponent(gventa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(agzapato))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(agcolor)))))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agsuela, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adm, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(resetclave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agzapatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agzapatoActionPerformed
        // TODO add your handling code here:
        
        az.setVisible(true);
    }//GEN-LAST:event_agzapatoActionPerformed

    private void admActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admActionPerformed
         bv.setVisible(true);
    }//GEN-LAST:event_admActionPerformed

    private void resetclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetclaveActionPerformed

    private void agclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agclienteActionPerformed
        // TODO add your handling code here:
       ac.setVisible(true);  
       // ac.setVisible(true);
    }//GEN-LAST:event_agclienteActionPerformed

    private void bzapatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bzapatoActionPerformed
        // TODO add your handling code here:
       bz.setVisible(true);
    }//GEN-LAST:event_bzapatoActionPerformed

    private void bclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclienteActionPerformed
        // TODO add your handling code here:
       bc.setVisible(true);
    }//GEN-LAST:event_bclienteActionPerformed

    private void gventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gventaActionPerformed
        // TODO add your handling code here:
        v.setVisible(true);
    }//GEN-LAST:event_gventaActionPerformed

    private void agcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agcolorActionPerformed
        // TODO add your handling code here:
        
        aco.setVisible(true);
    }//GEN-LAST:event_agcolorActionPerformed

    private void agsuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agsuelaActionPerformed
        // TODO add your handling code here:
        
        as.setVisible(true);
    }//GEN-LAST:event_agsuelaActionPerformed

    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adm;
    private javax.swing.JButton agcliente;
    private javax.swing.JButton agcolor;
    private javax.swing.JButton agsuela;
    private javax.swing.JButton agzapato;
    private javax.swing.JButton bcliente;
    private javax.swing.JButton bzapato;
    private javax.swing.JButton gventa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton resetclave;
    // End of variables declaration//GEN-END:variables
}
